[package]
name = "pallet-actors"
version = "2.0.0-rc2"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for actor-based smart contracts"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
pwasm-utils = { version = "0.12.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }
parity-wasm = { version = "0.41.0", default-features = false }
frame-support = { version = "2.0.0-rc2", default-features = false, path = "../support" }
frame-system = { version = "2.0.0-rc2", default-features = false, path = "../system" }
pallet-balances = { version = "2.0.0-rc2", default-features = false, path = "../balances" }
sp-core = { version = "2.0.0-rc2", default-features = false, path = "../../primitives/core" }
sp-runtime = { version = "2.0.0-rc2", default-features = false, path = "../../primitives/runtime" }
sp-io = { version = "2.0.0-rc2", default-features = false, path = "../../primitives/io" }
sp-std = { version = "2.0.0-rc2", default-features = false, path = "../../primitives/std" }
sp-sandbox = { version = "0.8.0-rc2", default-features = false, path = "../../primitives/sandbox" }
sp-arithmetic = { version = "2.0.0-rc2", default-features = false, path = "../../primitives/arithmetic" }

[dev-dependencies]
sp-core = { version = "2.0.0-rc2", path = "../../primitives/core", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"pwasm-utils/std",
	"wasmi-validation/std",
	"parity-wasm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-sandbox/std",
	"sp-arithmetic/std",
]
